name: Download and Modify Internal Manifest Files

on:
  schedule:
    - cron: '0 0 * * *' # Schedule the workflow to run daily

jobs:
  download_and_modify_manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch releases and download manifest files
        run: |
          releases=$(curl -s "https://api.github.com/repos/microsoft/FluidFramework/releases")
          internal_releases=$(echo "$releases" | jq -r '.[] | select(.name | contains("internal"))')
          
          for release in $internal_releases; do
            manifest_url=$(echo "$release" | jq -r '.assets[] | select(.name | contains("fluid-framework-release-manifest.client.")) | .browser_download_url')
            if [ -n "$manifest_url" ]; then
              echo "Downloading manifest: $manifest_url"
              curl -LOJ "$manifest_url"

              # Extract the filename from the URL
              manifest_filename=$(basename "$manifest_url")

              # Modify the downloaded manifest file
              sed -i 's/\"[a-zA-Z0-9_-]\+\": \">= [0-9]\+\.[0-9]\+-internal\.\([0-9]\+\.\)\+[0-9]\+ <[0-9]\+\.[0-9]\+-internal\.\([0-9]\+\.\)\+[0-9]\+\"/\"[a-zA-Z0-9_-]\+\": \"2.0.0-dev.1.0.0\"/' "$manifest_filename"
              
              # Commit the changes
              git config --global user.name "GitHub Actions"
              git config --global user.email "actions@github.com"
              git commit -am "Replace internal versions with dev.1.0.0 in $manifest_filename"
              git push
            fi
          done
